language: node_js
env:
  global:
  - secure: XeIeZm4hfUFwcmjJtFJjRDroG6H10ak6u9ClZOZXfJlRjpMAUyhVhPiUsc+7y6XcifFTPOdmWmQKAcxV/yBws/0s29HVQwvXhWyeZn0nfyyLIH3LuzOiwW1W2DDPxXaFeJSSG5ERmDdg5E0tLDRM4uJQsYGPyX9E6bMOczGhn/2vzhuGOIMpDx3MLfDnTfteFjSXfv+37FCxIbnuKVuhSuJuXhEISZuXw3TTCcyZuf/r69aJ+S2vG6g6JYjugc/DXPdbN1cY/nN8QBLRKKGyAXvq5hDnHuQKcyoGYIslG9dbBsVWlP/GmhyHeA9QfUo+CZC87wSpn20W8B81/ccRgccRf/ZUXkK7cymzQQyji3ZjWZTo7MQsM2nAK5fHLeiOcwcgWi+dluUxWqBB10WGMZZmaGLPIhsnnia6kQoSpOgR3HrMp1/+ivFvwQKDac9WV41tsPOxCggIgDNqVZJCOXY0wOqPvOcnHGkciTg5EFVSG7/VX0zY2cX46IFduP9V+T5dDovF116wzHLp83ndtfqwDFRg5/Ux7Xhvy3ejqQamLDmI1FjWTyuxqMN/uVBG1SVPONcY1Xp+AsBVdCmR3GzZC3fm7DOw0hP3ZLehv0YpsijJAZ+1vesn0uWV464QVAofCLDuQBjcJySkQgeLA73kWzPeO5AAtg/K33ougKw=
notifications:
  webhooks:
    urls:
    - secure: "Yzi1pr49QoaFW7AxYq56XXbakdcsqNeg9SlDDWek8CC3gz0HQlxXTufe5P+p1dwu6Glntl91bnQUEHbz83kY8hGhHxOxvh/gTDzBg3Ji7sJYyUGCOvoqayyg8c2eykFV2nL5ahdftx7Bd2u5dRDoteJoriGhkFPigZo+BkP+6oPbjww0EH2IgLa/eCo7H8mGvltAjah99P3zb1GdZgnuTTx5gmFN+jQF85VJ27rUsxmU08GZTjiEK06GNoJG0v7X9ssYKLSo3wG4J4wvtdjTusHEEwgXvCoyvwGIKBQYE+yshEUI4jdL+agQ51AJNGkevY1CMSGCgurx4dpVzQdwVFgKgkqHj6c6QO57j7h/yvCzJEZzSlBZ5nCurNTYTJKlQb4lHzH2no7apqV3zYTApHbNAyppdkuB9luWguNqGob4TkPQmaf1+RYb8Xa/EqYSYbk93lmMwEXJGytrJYh97N16hpp22Atp5ODB30NAnORkpAtQMgV6i2r8fgP+T/TpZErg2beKfuXXRRQ255NiC+Cwxh7/Keqx7syeo/iGV2nv6sB4QLjkl/PXJN1LgzxiD5dMM7/EguOKl1N56tkCiE795TYysC4KNu7DH+u8LfZLeimVYDowXPQBFI7BfDqGNVICciNpxNdX3uCgzDYgHg8WHAHY4J0yeVflqoW5fuk="
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
- npm
- yarn
install:
- yarn
script:
- yarn build
after_success:
- tar czvf tmp.tar.gz -C ./build .
- 'curl -F info="{\"mode\": \"build\", \"branchName\": \"${TRAVIS_BRANCH}\", \"description\":
  \"${TRAVIS_COMMIT_MESSAGE}(${TRAVIS_COMMIT})\", \"token\": \"${token}\"}" -F file=@tmp.tar.gz
  https://austudio.delbertbeta.cc/template/api/versions'
